rest:
  auth-open: true #jwt鉴权机制是否开启(true或者false)
  sign-open: true #签名机制是否开启(true或false)

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key
  ignore-url:

server:
  port: 8071

spring:
  application:
    name: tedu-gateway
  dubbo:
    server: true
    registry: zookeeper://localhost:2181
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xxx?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password:
    filters: log4j,wall,mergeStat

mybatis-plus:
  mapper-locations: classpath*:com/gdglc/tedu/rest/**/mapper/*.xml
    typeAliasesPackage: com.gdglc.tedy.rest.common.model
    global-config:
      id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
      db-column-underline: false
      refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: false
      cache-enabled: true #配置的缓存的全局开关
      lazyLoadingEnabled: true #延时加载的开关
      multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

redis:
  host: localhost
  port: 6379
  password:
  # 连接超时时间（毫秒）
  timeout: 10000
  pool:
    # 连接池中的最大空闲连接
    max-idle: 8
    # 连接池中的最小空闲连接
    min-idle: 10
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 100
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1

logging:
  level.root: info
  level.com.gdglc.tedu: debug
  path: logs/
  file: tedu-gateway.log
