server:
  port: 8072

spring:
  application:
    name: tedu-user
  dubbo:
    server: true
    registry: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20881

logging:
  level.root: info
  level.com.gdglc.tedu: debug
  path: logs/
  file: tedu-user.log